# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rserv',
            fields=[
                ('rserv_date', models.DateTimeField(primary_key=True, serialize=False)),
                ('reserved', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('book_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rserv_er', models.CharField(max_length=200)),
                ('rserv_call', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
