# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20171007_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='rserv',
            name='rserv_usernum',
            field=models.SmallIntegerField(default=2),
        ),
    ]
