# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_rserv_rserv_usernum'),
    ]

    operations = [
        migrations.AddField(
            model_name='rserv',
            name='rserv_room',
            field=models.SmallIntegerField(default=2),
        ),
    ]
