# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_rserv_rserv_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rserv',
            name='applied',
            field=models.BooleanField(default=False, verbose_name='확인여부'),
        ),
        migrations.AlterField(
            model_name='rserv',
            name='book_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='예약한날'),
        ),
        migrations.AlterField(
            model_name='rserv',
            name='reserved',
            field=models.BooleanField(default=False, verbose_name='예약여부'),
        ),
        migrations.AlterField(
            model_name='rserv',
            name='rserv_call',
            field=models.CharField(max_length=20, verbose_name='예약인 연락처'),
        ),
        migrations.AlterField(
            model_name='rserv',
            name='rserv_er',
            field=models.CharField(max_length=200, verbose_name='예약인'),
        ),
        migrations.AlterField(
            model_name='rserv',
            name='rserv_usernum',
            field=models.SmallIntegerField(default=2, verbose_name='신청인원'),
        ),
    ]
